pipeline {
  agent {
    kubernetes {
      cloud "openshift"
      label 'skopeo-pod'
      containerTemplate {
        name 'skopeo'
        image 'maven:3.3.9-jdk-8-alpine'
        resourceRequestMemory "1Gi"
        resourceLimitMemory "2Gi"
      }
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('skopeo') {
          sh 'mvn -version'
          sh 'skopeo --version'
        }
      }
    }
  }
}