pipeline {
  agent {
    kubernetes {
      cloud "openshift"
      label 'skopeo-pod'
      containerTemplate {
        name 'skopeo'
        image 'docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-slave-appdev'
      }
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('skopeo') {
          sh 'mvn -version'
          sh 'skopeo --version'
        }
      }
    }
  }
}