apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: dev-pipeline
  spec:
    source:
      git:
        ref: pipeline
        uri: https://github.com/laugimethods/advdev_homework_template.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
##        path: ParksMap/Jenkinsfile
        jenkinsfilePath: Infrastructure/templates/Jenkinsfile
