apiVersion: v1
kind: Template
parameters:
- name: HOST
  description: Application Host URL - Like jenkins-project-jenkins.apps.na39.openshift.opentlc.com
metadata:
  creationTimestamp: null
  name: jenkins
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    creationTimestamp: null
    generation: 1
    labels:
      app: jenkins-persistent
      template: jenkins-persistent-template
    name: jenkins
    ownerReferences:
    - apiVersion: template.openshift.io/v1
      blockOwnerDeletion: true
      kind: TemplateInstance
      name: 1bd7b6e5-60a7-40b3-81f7-18faf76edbd0
      uid: 83ad8832-7ad1-11e8-8dcf-0220bffb280e
  spec:
    replicas: 1
    selector:
      name: jenkins
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: jenkins
      spec:
        containers:
        - env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "false"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: JENKINS_SERVICE_NAME
            value: jenkins
          - name: JNLP_SERVICE_NAME
            value: jenkins-jnlp
          image: registry.access.redhat.com/openshift3/jenkins-2-rhel7@sha256:b0c2a46307fafbc6f28d5b01d0c818b371953faf021e44468acf0e54a42f0aa0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            periodSeconds: 360
            successThreshold: 1
            timeoutSeconds: 240
          name: jenkins
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: jenkins
        serviceAccountName: jenkins
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: jenkins:2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 4m
      openshift.io/host.generated: "true"
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    creationTimestamp: null
    labels:
      app: jenkins-persistent
      template: jenkins-persistent-template
    name: jenkins
    ownerReferences:
    - apiVersion: template.openshift.io/v1
      blockOwnerDeletion: true
      kind: TemplateInstance
      name: 1bd7b6e5-60a7-40b3-81f7-18faf76edbd0
      uid: 83ad8832-7ad1-11e8-8dcf-0220bffb280e
  spec:
    host: ${HOST}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: jenkins
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-06-28T12:48:11Z
        status: "True"
        type: Admitted
      host: ${HOST}
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
        jenkins; cpu limit for container jenkins'
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: jenkins
      openshift.io/deployment.name: jenkins-1
      openshift.io/scc: restricted
    creationTimestamp: null
    generateName: jenkins-1-
    labels:
      deployment: jenkins-1
      deploymentconfig: jenkins
      name: jenkins
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: jenkins-1
      uid: 83b6ca37-7ad1-11e8-8dcf-0220bffb280e
  spec:
    containers:
    - env:
      - name: OPENSHIFT_ENABLE_OAUTH
        value: "false"
      - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
        value: "true"
      - name: KUBERNETES_MASTER
        value: https://kubernetes.default:443
      - name: KUBERNETES_TRUST_CERTIFICATES
        value: "true"
      - name: JENKINS_SERVICE_NAME
        value: jenkins
      - name: JNLP_SERVICE_NAME
        value: jenkins-jnlp
      image: registry.access.redhat.com/openshift3/jenkins-2-rhel7@sha256:b0c2a46307fafbc6f28d5b01d0c818b371953faf021e44468acf0e54a42f0aa0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 2
        httpGet:
          path: /login
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 420
        periodSeconds: 360
        successThreshold: 1
        timeoutSeconds: 240
      name: jenkins
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 240
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 512Mi
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        privileged: false
        runAsUser: 1006130000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/lib/jenkins
        name: jenkins-data
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: jenkins-token-krdr2
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: jenkins-dockercfg-fwhn4
    nodeName: node1.na39.internal
    nodeSelector:
      env: users
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1006130000
      seLinuxOptions:
        level: s0:c78,c62
    serviceAccount: jenkins
    serviceAccountName: jenkins
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    volumes:
    - name: jenkins-data
      persistentVolumeClaim:
        claimName: jenkins
    - name: jenkins-token-krdr2
      secret:
        defaultMode: 420
        secretName: jenkins-token-krdr2
  status:
    phase: Pending
    qosClass: Burstable
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.completed-at: 2018-06-28 12:53:04 +0000 UTC
      openshift.io/deployer-pod.created-at: 2018-06-28 12:48:11 +0000 UTC
      openshift.io/deployer-pod.name: jenkins-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: jenkins
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: config change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"jenkins","namespace":"lm-jenkins","selfLink":"/apis/apps.openshift.io/v1/namespaces/lm-jenkins/deploymentconfigs/jenkins","uid":"83b24335-7ad1-11e8-8dcf-0220bffb280e","resourceVersion":"5483487","generation":2,"creationTimestamp":"2018-06-28T12:48:11Z","labels":{"app":"jenkins-persistent","template":"jenkins-persistent-template"},"annotations":{"template.alpha.openshift.io/wait-for-ready":"true"},"ownerReferences":[{"apiVersion":"template.openshift.io/v1","kind":"TemplateInstance","name":"1bd7b6e5-60a7-40b3-81f7-18faf76edbd0","uid":"83ad8832-7ad1-11e8-8dcf-0220bffb280e","blockOwnerDeletion":true}]},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["jenkins"],"from":{"kind":"ImageStreamTag","namespace":"openshift","name":"jenkins:2"},"lastTriggeredImage":"registry.access.redhat.com/openshift3/jenkins-2-rhel7@sha256:b0c2a46307fafbc6f28d5b01d0c818b371953faf021e44468acf0e54a42f0aa0"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"name":"jenkins"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"jenkins"}},"spec":{"volumes":[{"name":"jenkins-data","persistentVolumeClaim":{"claimName":"jenkins"}}],"containers":[{"name":"jenkins","image":"registry.access.redhat.com/openshift3/jenkins-2-rhel7@sha256:b0c2a46307fafbc6f28d5b01d0c818b371953faf021e44468acf0e54a42f0aa0","env":[{"name":"OPENSHIFT_ENABLE_OAUTH","value":"false"},{"name":"OPENSHIFT_ENABLE_REDIRECT_PROMPT","value":"true"},{"name":"KUBERNETES_MASTER","value":"https://kubernetes.default:443"},{"name":"KUBERNETES_TRUST_CERTIFICATES","value":"true"},{"name":"JENKINS_SERVICE_NAME","value":"jenkins"},{"name":"JNLP_SERVICE_NAME","value":"jenkins-jnlp"}],"resources":{"limits":{"memory":"512Mi"}},"volumeMounts":[{"name":"jenkins-data","mountPath":"/var/lib/jenkins"}],"livenessProbe":{"httpGet":{"path":"/login","port":8080,"scheme":"HTTP"},"initialDelaySeconds":420,"timeoutSeconds":240,"periodSeconds":360,"successThreshold":1,"failureThreshold":2},"readinessProbe":{"httpGet":{"path":"/login","port":8080,"scheme":"HTTP"},"initialDelaySeconds":3,"timeoutSeconds":240,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{},"privileged":false}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"jenkins","serviceAccount":"jenkins","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":0,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]}}}
    creationTimestamp: null
    generation: 1
    labels:
      app: jenkins-persistent
      openshift.io/deployment-config.name: jenkins
      template: jenkins-persistent-template
    name: jenkins-1
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: jenkins
      uid: 83b24335-7ad1-11e8-8dcf-0220bffb280e
  spec:
    replicas: 1
    selector:
      deployment: jenkins-1
      deploymentconfig: jenkins
      name: jenkins
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: jenkins
          openshift.io/deployment.name: jenkins-1
        creationTimestamp: null
        labels:
          deployment: jenkins-1
          deploymentconfig: jenkins
          name: jenkins
      spec:
        containers:
        - env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "false"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: JENKINS_SERVICE_NAME
            value: jenkins
          - name: JNLP_SERVICE_NAME
            value: jenkins-jnlp
          image: registry.access.redhat.com/openshift3/jenkins-2-rhel7@sha256:b0c2a46307fafbc6f28d5b01d0c818b371953faf021e44468acf0e54a42f0aa0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            periodSeconds: 360
            successThreshold: 1
            timeoutSeconds: 240
          name: jenkins
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: jenkins
        serviceAccountName: jenkins
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "jenkins-jnlp", "namespace":
        "", "kind": "Service"}]'
      service.openshift.io/infrastructure: "true"
    creationTimestamp: null
    labels:
      app: jenkins-persistent
      template: jenkins-persistent-template
    name: jenkins
    ownerReferences:
    - apiVersion: template.openshift.io/v1
      blockOwnerDeletion: true
      kind: TemplateInstance
      name: 1bd7b6e5-60a7-40b3-81f7-18faf76edbd0
      uid: 83ad8832-7ad1-11e8-8dcf-0220bffb280e
  spec:
    ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      name: jenkins
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: jenkins-persistent
      template: jenkins-persistent-template
    name: jenkins-jnlp
    ownerReferences:
    - apiVersion: template.openshift.io/v1
      blockOwnerDeletion: true
      kind: TemplateInstance
      name: 1bd7b6e5-60a7-40b3-81f7-18faf76edbd0
      uid: 83ad8832-7ad1-11e8-8dcf-0220bffb280e
  spec:
    ports:
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      name: jenkins
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
